-- Insert 15 dummy profiles (7 brides, 8 grooms) with complete data
-- These profiles will populate the matrimony platform with sample data for testing

-- Insert 7 Bride Profiles
INSERT INTO profiles (
  user_id,
  email,
  full_name,
  gender,
  date_of_birth,
  phone,
  city,
  profession,
  education,
  height,
  weight,
  bio,
  gotra,
  rashi,
  nakshatra,
  horoscope_match,
  is_verified,
  verification_status,
  profile_photo_url,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'priya.sharma@example.com',
  'Priya Sharma',
  'Female',
  '1997-03-15'::date,
  '+91-9876543210',
  'Bangalore',
  'Software Engineer',
  'B.Tech (Computer Science)',
  '5.4',
  '52',
  'Passionate about technology and exploring new cultures. Love reading and yoga.',
  'Kasyapa',
  'Libra',
  'Ashwini',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/bride-1.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'anjali.patel@example.com',
  'Anjali Patel',
  'Female',
  '1998-07-22'::date,
  '+91-9876543211',
  'Mumbai',
  'Doctor',
  'MBBS, MD Pathology',
  '5.5',
  '53',
  'Dedicated physician with a passion for helping others. Enjoys traveling and cooking.',
  'Vasishtha',
  'Virgo',
  'Bharani',
  'Excellent',
  true,
  'verified',
  '/dummy-profiles/bride-2.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'neha.verma@example.com',
  'Neha Verma',
  'Female',
  '1996-11-08'::date,
  '+91-9876543212',
  'Delhi',
  'Finance Analyst',
  'MBA Finance, B.Com',
  '5.3',
  '51',
  'Results-oriented professional in finance sector. Adventure seeker and foodie.',
  'Bhrigu',
  'Aries',
  'Krittika',
  'Good',
  true,
  'verified',
  '/dummy-profiles/bride-3.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'kavya.singh@example.com',
  'Kavya Singh',
  'Female',
  '1999-05-30'::date,
  '+91-9876543213',
  'Pune',
  'Architect',
  'B.Arch, M.Arch',
  '5.4',
  '52',
  'Creative architect with eye for design. Loves art, music, and outdoor activities.',
  'Atri',
  'Taurus',
  'Rohini',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/bride-4.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'sunita.gupta@example.com',
  'Sunita Gupta',
  'Female',
  '1995-09-12'::date,
  '+91-9876543214',
  'Bangalore',
  'HR Manager',
  'MBA HR, B.A',
  '5.5',
  '54',
  'People-focused professional with leadership experience. Enjoys yoga and meditation.',
  'Kutsa',
  'Cancer',
  'Punarvasu',
  'Excellent',
  true,
  'verified',
  '/dummy-profiles/bride-5.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'meera.reddy@example.com',
  'Meera Reddy',
  'Female',
  '1997-01-25'::date,
  '+91-9876543215',
  'Hyderabad',
  'Teacher',
  'M.Ed, B.Ed',
  '5.3',
  '50',
  'Passionate educator dedicated to student development. Loves reading and travel.',
  'Gautama',
  'Leo',
  'Magha',
  'Good',
  true,
  'verified',
  '/dummy-profiles/bride-6.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'divya.nair@example.com',
  'Divya Nair',
  'Female',
  '1998-06-18'::date,
  '+91-9876543216',
  'Chennai',
  'Content Creator',
  'Bachelor of Media Studies',
  '5.4',
  '52',
  'Creative content creator with digital marketing expertise. Adventure and nature lover.',
  'Vishvamitra',
  'Sagittarius',
  'Uttara Phalguni',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/bride-7.jpg',
  NOW(),
  NOW()
);

-- Insert 8 Groom Profiles
INSERT INTO profiles (
  user_id,
  email,
  full_name,
  gender,
  date_of_birth,
  phone,
  city,
  profession,
  education,
  height,
  weight,
  bio,
  gotra,
  rashi,
  nakshatra,
  horoscope_match,
  is_verified,
  verification_status,
  profile_photo_url,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'rahul.kumar@example.com',
  'Rahul Kumar',
  'Male',
  '1995-02-10'::date,
  '+91-9876543220',
  'Bangalore',
  'Software Developer',
  'B.Tech IIT, M.Tech',
  '5.10',
  '75',
  'Passionate developer with 6+ years in tech. Love coding, hiking, and exploring new places.',
  'Kasyapa',
  'Libra',
  'Ashwini',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/groom-1.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'arjun.patel@example.com',
  'Arjun Patel',
  'Male',
  '1994-08-22'::date,
  '+91-9876543221',
  'Mumbai',
  'Investment Banker',
  'MBA IIM, B.Com',
  '5.11',
  '77',
  'Result-driven professional in finance with global exposure. Sports enthusiast.',
  'Vasishtha',
  'Virgo',
  'Bharani',
  'Excellent',
  true,
  'verified',
  '/dummy-profiles/groom-2.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'vikram.singh@example.com',
  'Vikram Singh',
  'Male',
  '1996-04-14'::date,
  '+91-9876543222',
  'Delhi',
  'Civil Engineer',
  'B.Tech, M.Tech',
  '5.9',
  '76',
  'Experienced engineer with infrastructure projects. Loves traveling and photography.',
  'Bhrigu',
  'Aries',
  'Krittika',
  'Good',
  true,
  'verified',
  '/dummy-profiles/groom-3.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'aditya.desai@example.com',
  'Aditya Desai',
  'Male',
  '1997-12-28'::date,
  '+91-9876543223',
  'Pune',
  'Product Manager',
  'MBA, B.Tech',
  '5.10',
  '74',
  'Strategic product manager with startup experience. Fitness enthusiast and entrepreneur.',
  'Atri',
  'Taurus',
  'Rohini',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/groom-4.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'karan.jain@example.com',
  'Karan Jain',
  'Male',
  '1993-10-05'::date,
  '+91-9876543224',
  'Bangalore',
  'Entrepreneur',
  'B.B.A, Startup Founder',
  '5.11',
  '78',
  'Successful startup founder with passion for innovation. Love mentoring and business.',
  'Kutsa',
  'Cancer',
  'Punarvasu',
  'Excellent',
  true,
  'verified',
  '/dummy-profiles/groom-5.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'sanjay.sharma@example.com',
  'Sanjay Sharma',
  'Male',
  '1995-07-16'::date,
  '+91-9876543225',
  'Hyderabad',
  'Consultant',
  'MBA, B.E',
  '5.10',
  '75',
  'Management consultant with international exposure. Enjoys cricket and music.',
  'Gautama',
  'Leo',
  'Magha',
  'Good',
  true,
  'verified',
  '/dummy-profiles/groom-6.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'rohan.malhotra@example.com',
  'Rohan Malhotra',
  'Male',
  '1996-03-20'::date,
  '+91-9876543226',
  'Chennai',
  'Architect',
  'B.Arch, M.Arch',
  '5.9',
  '73',
  'Creative architect designing sustainable buildings. Passionate about design and innovation.',
  'Vishvamitra',
  'Sagittarius',
  'Uttara Phalguni',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/groom-7.jpg',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'nikhil.tiwari@example.com',
  'Nikhil Tiwari',
  'Male',
  '1998-05-09'::date,
  '+91-9876543227',
  'Bangalore',
  'Data Scientist',
  'M.Tech (AI/ML), B.Tech',
  '5.10',
  '74',
  'AI and ML specialist working on cutting-edge projects. Tech enthusiast and innovator.',
  'Agastya',
  'Pisces',
  'Ashlesha',
  'Perfect',
  true,
  'verified',
  '/dummy-profiles/groom-8.jpg',
  NOW(),
  NOW()
);

-- Mark some profiles as featured for the carousel
UPDATE profiles 
SET is_featured = true 
WHERE email IN (
  'priya.sharma@example.com',
  'anjali.patel@example.com',
  'rahul.kumar@example.com',
  'arjun.patel@example.com',
  'vikram.singh@example.com'
);

-- Insert featured profiles data
INSERT INTO featured_profiles (profile_id, featured_position, featured_from, featured_to)
SELECT 
  id,
  ROW_NUMBER() OVER (ORDER BY created_at),
  NOW(),
  NOW() + INTERVAL '90 days'
FROM profiles
WHERE email IN (
  'priya.sharma@example.com',
  'anjali.patel@example.com',
  'rahul.kumar@example.com',
  'arjun.patel@example.com',
  'vikram.singh@example.com'
);
